# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: New features
      labels:
        - "Topic: Enhancement"
        - "Topic: Help wanted"
    - title: In progress
      labels:
        - "Topic: In progress"
    - title: Translation updates
      labels:
        - "Topic: Translations"
    - title: Bug fixes
      labels:
        - "Topic: Bug"
        - "Topic: Invalid"
    - title: Removed features
      labels:
        - "Topic: For remove"
    - title: Dependencies
      labels:
        - "Topic: Dependencies"
    - title: Build system improvements
      labels:
        - "Topic: Build System"
    - title: DLCs
      labels:
        - "Topic: DLCs"
    - title: SDK
      labels:
        - "Topic: SDK"
    - title: Linux
      labels:
        - "OS: Linux"
    - title: Windows
      labels:
        - "OS: Windows"
    - title: OSX
      labels:
        - "OS: OSX"
    - title: Other Changes
      labels:
        - "*"
