# This is a basic workflow to help you get started with Actions

name: Android export

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'
    branches: [ master ]
    paths-ignore:
    - 'game_version.txt'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Export Android
        uses: croconut/godot-multi-builder@v1
        with:
      #comma separated export presets
          names: "Android"
        # defaults to true, Android currently only exports to debug
          debug-mode: "true"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
           name: build-android
    # A file, directory or wildcard pattern that describes what to upload
           path: builds/builds.zip
