# This is a basic workflow to help you get started with Actions

name: Gdnative

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile-gdnative-x11:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python (for SCons)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qqq build-essential pkg-config gcc-multilib g++-multilib
        python -m pip install scons
    - name: Compile
      run: |
        cd cpp
        mkdir -p demo/bin/
        git clone --recursive https://github.com/godotengine/godot-cpp -b 3.3
        cd godot-cpp
        scons platform=linux generate_bindings=yes target=release -j $(nproc)
        cd ../
        scons platform=linux target=release -j $(nproc) target_name=FoxyAdventureSDK.Core.so
    - name: Upload a Build Artifact Linux
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-godot-cpp-x11
        path: cpp/demo/bin/
  compile-gdnative-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set up Python (for SCons)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: Install dependencies
      run: |
        python -m pip install scons
    - name: Compile
      run: |
        cd cpp
        mkdir -p demo/bin/
        git clone --recursive https://github.com/godotengine/godot-cpp -b 3.3
        cd godot-cpp
        scons platform=windows generate_bindings=yes target=release -j $env:NUMBER_OF_PROCESSORS
        cd ../
        scons platform=windows target=release -j $env:NUMBER_OF_PROCESSORS target_name=FoxyAdventureSDK.Core.dll
    - name: Upload a Build Artifact Windows
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-godot-cpp-win
        path: cpp/demo/bin/
  compile-gdnative-osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2.4.0
    - name: Set up Python (for SCons)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: Install dependencies
      run: |
        python -m pip install scons
    - name: Compile
      run: |
        cd cpp
        mkdir -p demo/bin/
        git clone --recursive https://github.com/godotengine/godot-cpp -b 3.3
        cd godot-cpp
        scons platform=osx generate_bindings=yes target=release -j $(sysctl -n hw.logicalcpu)
        cd ../
        scons platform=osx target=release -j $(sysctl -n hw.logicalcpu) target_name=FoxyAdventureSDK.Core.dylib
    - name: Upload a Build Artifact Windows
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-godot-cpp-osx
        path: cpp/demo/bin/
