# This is a basic workflow to help you get started with Actions

name: Godot Build PC Artifact

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  godot-build:
    continue-on-error: true
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        godot-version: [3.4]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.4.0
      # Runs a set of commands using the runners shell
      - name: Read version file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.dat
      - name: Build everything
        run: |
          sudo chmod +x ./build_game.sh
          ./build_game.sh -godot_version_number ${{ matrix.godot-version }} -godot_version_status "stable" -build_mode "source" -base_path $GITHUB_WORKSPACE -branch "main"
          zip -r build-x11-64-${{ matrix.godot-version }}.zip builds/${{ matrix.godot-version }}.stable/x11-64-standard/
          zip -r build-osx-${{ matrix.godot-version }}.zip builds/${{ matrix.godot-version }}.stable/osx-standard/
          zip -r build-win-64-${{ matrix.godot-version }}.zip builds/${{ matrix.godot-version }}.stable/win-64-standard/
      - name: Upload a Build Artifact win
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: win-64-standard
          # A file, directory or wildcard pattern that describes what to upload
          path: build-win-64-${{ matrix.godot-version }}.zip
          # The desired behavior if no files are found using the provided path.
      - name: Upload a Build Artifact x11
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: x11-64-standard
          # A file, directory or wildcard pattern that describes what to upload
          path: build-x11-64-${{ matrix.godot-version }}.zip
          # The desired behavior if no files are found using the provided path.
      - name: Upload a Build Artifact osx
        uses: actions/upload-artifact@v2.3.1
        with:
          # Artifact name
          name: osx-standard
          # A file, directory or wildcard pattern that describes what to upload
          path: build-osx-${{ matrix.godot-version }}.zip
          # The desired behavior if no files are found using the provided path.
  installer-build:
    needs: godot-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Read version file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.dat
      - name: Download files
        uses: actions/download-artifact@v2
        with:
          path: game_builds
      - name: Build Installers
        run: |
          mkdir D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\windows
          mkdir D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\osx
          mkdir D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\x11
          echo "unzipping game data"
          powershell Expand-Archive -Path D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\win-64-standard\build-win-64-3.4.zip -DestinationPath D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\windows
          powershell Expand-Archive -Path D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\osx-standard\build-osx-3.4.zip -DestinationPath D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\osx
          powershell Expand-Archive -Path D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\x11-64-standard\build-x11-64-3.4.zip -DestinationPath D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\x11
          echo "game data unzipped"
          mkdir D:\a\Foxy-Adventure\Foxy-Adventure\output_installer
          D:\a\Foxy-Adventure\Foxy-Adventure/install_builder/bin/builder-cli.exe build D:\a\Foxy-Adventure\Foxy-Adventure/install_builder/foxyadventure.xml linux-x64 --setvars project.outputDirectory=D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\ project.version=${{ steps.package.outputs.content }}
          D:\a\Foxy-Adventure\Foxy-Adventure\install_builder/bin/builder-cli.exe build D:\a\Foxy-Adventure\Foxy-Adventure/install_builder/foxyadventure.xml windows-x64 --setvars project.outputDirectory=D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\ project.version=${{ steps.package.outputs.content }}
          D:\a\Foxy-Adventure\Foxy-Adventure\install_builder/bin/builder-cli.exe build D:\a\Foxy-Adventure\Foxy-Adventure/install_builder/foxyadventure.xml osx --setvars project.outputDirectory=D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\ project.version=${{ steps.package.outputs.content }}
          cd D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\
          tree /f
          powershell Compress-Archive "D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\FoxyAdventureInstaller-osx.app" "D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\FoxyAdventureInstaller-osx.app.zip"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.package.outputs.content }}
          release_name: Release ${{ steps.package.outputs.content }}
          draft: false
          prerelease: false
      - name: Upload Release Asset - x11
        id: upload-release-asset-x11 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\FoxyAdventureInstaller-linux-x64.run
          asset_name: FoxyAdventureInstaller-linux-x64.run
          asset_content_type: application/octet-stream
      - name: Upload Release Asset - x11
        id: upload-release-asset-x112
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\x11-64-standard\build-x11-64-3.4.zip
          asset_name: build-x11-64-3.4.zip
          asset_content_type: application/zip
      - name: Upload Release Asset - osx
        id: upload-release-asset-osx
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\FoxyAdventureInstaller-osx.app.zip
          asset_name: FoxyAdventureInstaller-osx.app.zip
          asset_content_type: application/zip
      - name: Upload Release Asset - osx
        id: upload-release-asset-osx2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\osx-standard\build-osx-3.4.zip
          asset_name: build-osx-3.4.zip
          asset_content_type: application/zip
      - name: Upload Release Asset - win
        id: upload-release-asset-win
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: D:\a\Foxy-Adventure\Foxy-Adventure\output_installer\FoxyAdventureInstaller-windows-x64.exe
          asset_name: FoxyAdventureInstaller-windows-64.exe
          asset_content_type: application/octet-stream
      - name: Upload Release Asset - win
        id: upload-release-asset-win2
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: D:\a\Foxy-Adventure\Foxy-Adventure\game_builds\win-64-standard\build-win-64-3.4.zip
          asset_name: build-win-64-3.4.zip
          asset_content_type: application/zip
          
