# This is a basic workflow to help you get started with Actions

name: Godot Build PC Artifact

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop, new-github-actions ]
  pull_request:
    branches: [ master, develop, new-github-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  crashreport-build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pywin32
          pip install tk
          pip install pyinstaller
          ./build_crashreport_windows.bat
      - name: Upload a Build Artifact Windows
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-windows
          path: crashreport/win/dist
  crashreport-build-osx:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install tk
          pip install pyinstaller
          sudo chmod +x ./build_crashreport_osx.sh
          ./build_crashreport_osx.sh
      - name: Upload a Build Artifact osx
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-osx
          path: crashreport/osx/dist
  crashreport-build-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install tk
          pip install pyinstaller
          sudo chmod +x ./build_crashreport_linux.sh
          ./build_crashreport_linux.sh
      - name: Upload a Build Artifact x11-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-x11-64
          path: crashreport/x11/dist
  # This workflow contains a single job called "build"
  godot-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    needs: [compile-gdnative-x11, compile-gdnative-windows, compile-gdnative-osx]
    strategy:
      matrix:
        godot-version: [3.3.3]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
      # Runs a set of commands using the runners shell
      - uses: actions/download-artifact@v2
        with:
          name: build-godot-cpp-osx
          path: cpp/demo/bin
      - uses: actions/download-artifact@v2
        with:
          name: build-godot-cpp-win
          path: cpp/demo/bin
      - uses: actions/download-artifact@v2
        with:
          name: build-godot-cpp-x11
          path: cpp/demo/bin
      - name: Build everything
        run: |
          sudo chmod +x ./build_game.sh
          ./build_game.sh -godot_version_number ${{ matrix.godot-version }} -godot_version_status "stable"
      - name: Upload a Build Artifact x11-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-x11-64-${{ matrix.godot-version }}
          path: builds/${{ matrix.godot-version }}.stable/x11-64-standard
      - name: Upload a Build Artifact osx-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-osx-64-${{ matrix.godot-version }}
          path: builds/${{ matrix.godot-version }}.stable/osx-standard
      - name: Upload a Build Artifact win-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-win-64-${{ matrix.godot-version }}
          path: builds/${{ matrix.godot-version }}.stable/win-64-standard
  crashreport-build-windows-signed:
    runs-on: ubuntu-18.04
    needs: [crashreport-build-windows]
    steps:
      - name: Download certificate and install packages
        run: |
          sudo apt-get update
          sudo apt-get install libnss3-tools build-essential pkg-config libssl-dev libcurl4-openssl-dev
          sudo apt-get install -y osslsigncode
          wget "https://newdev.web.app/dl/files/downloads/foxy-adventure/foxyadventurecrashreport.p12"
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Windows signtool.exe code sign action
        run: |
          cd $GITHUB_WORKSPACE/artifacts/build-crashreport-windows/send_log/
          cp send_log.exe sendlog.exe
          osslsigncode sign -pkcs12 $GITHUB_WORKSPACE/foxyadventurecrashreport.p12 -pass "foxyadventurecrashreport" \
          -n "Foxy Adventure Crash Report" -i "https://newdev.web.app" \
          -in sendlog.exe -out send_log.exe
          rm sendlog.exe
      - name: Upload a Build Artifact Windows
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-windows-signed
          path: artifacts/build-crashreport-windows/
  do-release:
    runs-on: ubuntu-18.04
    needs: [godot-build, crashreport-build-windows-signed, crashreport-build-linux, crashreport-build-osx]
    strategy:
      matrix:
        godot-version: [3.3.3]
    steps:
    - uses: actions/checkout@v2
    - name: Declare some variables
      id: vars
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Prepare files for releasing
      run: |
        cd $GITHUB_WORKSPACE/artifacts
        cp -r build-crashreport-osx/send_log/ build-osx-64-${{ matrix.godot-version }}
        cp -r build-crashreport-x11-64/send_log/ build-x11-64-${{ matrix.godot-version }}
        cp -r build-crashreport-windows-signed/send_log/ build-win-64-${{ matrix.godot-version }}
        cd $GITHUB_WORKSPACE/artifacts/build-osx-64-${{ matrix.godot-version }}
        sudo zip -r build-osx-64-${{ matrix.godot-version }}.zip *
        cd $GITHUB_WORKSPACE/artifacts/build-x11-64-${{ matrix.godot-version }}
        sudo zip -r build-x11-64-${{ matrix.godot-version }}.zip *
        cd $GITHUB_WORKSPACE/artifacts/build-win-64-${{ matrix.godot-version }}
        sudo zip -r build-win-64-${{ matrix.godot-version }}.zip *
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.vars.outputs.sha_short }}-${{ matrix.godot-version }}
        release_name: Release ${{ steps.vars.outputs.sha_short }} - ${{ matrix.godot-version }}
        draft: false
        prerelease: false
    - name: Upload Release Asset - x11-64 - ${{ matrix.godot-version }}
      id: upload-release-asset-x1164
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: artifacts/build-x11-64-${{ matrix.godot-version }}/build-x11-64-${{ matrix.godot-version }}.zip
        asset_name: build-x11-64-${{ matrix.godot-version }}.zip
        asset_content_type: application/zip
    - name: Upload Release Asset - osx-64 - ${{ matrix.godot-version }}
      id: upload-release-asset-osx64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: artifacts/build-osx-64-${{ matrix.godot-version }}/build-osx-64-${{ matrix.godot-version }}.zip
        asset_name: build-osx-64-${{ matrix.godot-version }}.zip
        asset_content_type: application/zip
    - name: Upload Release Asset - win-64 - ${{ matrix.godot-version }}
      id: upload-release-asset-win64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: artifacts/build-win-64-${{ matrix.godot-version }}/build-win-64-${{ matrix.godot-version }}.zip
        asset_name: build-win-64-${{ matrix.godot-version }}.zip
        asset_content_type: application/zip
  delete-artifacts:
    runs-on: ubuntu-18.04
    needs: [do-release, godot-build, crashreport-build-windows, crashreport-build-linux, crashreport-build-osx]
    strategy:
      matrix:
        godot-version: [3.3.3]
    steps:
    - uses: actions/checkout@v1
    - uses: geekyeggo/delete-artifact@v1
      with:
        name: |
          build-win-64-${{ matrix.godot-version }}
          build-osx-64-${{ matrix.godot-version }}
          build-x11-64-${{ matrix.godot-version }}
          build-crashreport-x11-64
          build-crashreport-osx
          build-crashreport-windows
          build-crashreport-windows-signed
  compile-gdnative-x11:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python (for SCons)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qqq build-essential pkg-config gcc-multilib g++-multilib
        python -m pip install scons
    - name: Compile
      run: |
        cd cpp
        mkdir -p demo/bin/
        git clone --recursive https://github.com/godotengine/godot-cpp
        cd godot-cpp
        scons platform=linux generate_bindings=yes target=release -j $(nproc)
        cd ../
        scons platform=linux target=release -j $(nproc) target_name=FoxyAdventureSDK.Core.so
    - name: Upload a Build Artifact Linux
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-godot-cpp-x11
        path: cpp/demo/bin/
  compile-gdnative-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Set up Python (for SCons)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: Install dependencies
      run: |
        python -m pip install scons
    - name: Compile
      run: |
        cd cpp
        mkdir -p demo/bin/
        git clone --recursive https://github.com/godotengine/godot-cpp
        cd godot-cpp
        scons platform=windows generate_bindings=yes target=release -j $env:NUMBER_OF_PROCESSORS
        cd ../
        scons platform=windows target=release -j $env:NUMBER_OF_PROCESSORS target_name=FoxyAdventureSDK.Core.dll
    - name: Upload a Build Artifact Windows
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-godot-cpp-win
        path: cpp/demo/bin/
  compile-gdnative-osx:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python (for SCons)
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.1'

    - name: Install dependencies
      run: |
        python -m pip install scons
    - name: Compile
      run: |
        cd cpp
        mkdir -p demo/bin/
        git clone --recursive https://github.com/godotengine/godot-cpp
        cd godot-cpp
        scons platform=osx generate_bindings=yes target=release -j $(sysctl -n hw.logicalcpu)
        cd ../
        scons platform=osx target=release -j $(sysctl -n hw.logicalcpu) target_name=FoxyAdventureSDK.Core.dylib
    - name: Upload a Build Artifact Windows
      uses: actions/upload-artifact@v2.2.4
      with:
        name: build-godot-cpp-osx
        path: cpp/demo/bin/
