# This is a basic workflow to help you get started with Actions

name: Godot Build PC Artifact

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop, new-github-actions ]
  pull_request:
    branches: [ master, develop, new-github-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  crashreport-build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install appdirs easygui pyinstaller
        run: |
          sudo chmod +x ./build_crashreport_windows.bat
          ./build_crashreport_windows.bat
      - name: Upload a Build Artifact Windows
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-windows
          path: crashreport/win/dist
  crashreport-build-osx:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install appdirs easygui pyinstaller
        run: |
          sudo chmod +x ./build_crashreport_osx.sh
          ./build_crashreport_osx.sh
      - name: Upload a Build Artifact osx
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-osx
          path: crashreport/osx/dist
  crashreport-build-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install appdirs easygui pyinstaller
        run: |
          sudo chmod +x ./build_crashreport_linux.sh
          ./build_crashreport_linux.sh
      - name: Upload a Build Artifact x11-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-crashreport-x11-64
          path: crashreport/x11/dist
  # This workflow contains a single job called "build"
  godot-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4
      # Runs a set of commands using the runners shell
      - name: Build everything
        run: |
          sudo chmod +x ./build_game.sh
          ./build_game.sh
      - name: Upload a Build Artifact x11-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-x11-64
          path: builds/x11-64-standard
      - name: Upload a Build Artifact osx-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-osx-64
          path: builds/osx-standard
      - name: Upload a Build Artifact win-64
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-win-64
          path: builds/win-64-standard
