# This is a basic workflow to help you get started with Actions

name: Godot Build PC Artifact

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  godot-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: Download Godot and export templates
        run: |
          sudo apt install unzip
          sudo apt install tree
          echo *** Downloading Godot Binary ***
          wget https://downloads.tuxfamily.org/godotengine/3.2.4/rc3/Godot_v3.2.4-rc3_linux_headless.64.zip
          echo *** Downloading Godot Server Export Templates ***
          wget https://downloads.tuxfamily.org/godotengine/3.2.4/rc3/Godot_v3.2.4-rc3_export_templates.tpz
          echo *** Unzipping Godot Binary ***
          unzip Godot_v3.2.4-rc3_linux_headless.64.zip
          echo *** Unzipping Godot Server Export Templates ***
          unzip Godot_v3.2.4-rc3_export_templates.tpz
          echo *** Installing Godot Server Export Templates ***
          cd /home/runner/
          sudo mkdir -p .local/share/godot
          cd .local/share/godot
          sudo mkdir -p templates/3.2.4.rc3
          sudo cp -r $GITHUB_WORKSPACE/templates/* templates/3.2.4.rc3
          echo *** Exporting Files ***
          cd $GITHUB_WORKSPACE
          sudo mkdir -p builds/{x11-64-standard,win-64-standard,osx-standard}
      - name: Export x11-64
        run: |
          sudo ./Godot_v3.2.4-rc3_linux_headless.64 --path "." --export "x11-64" $GITHUB_WORKSPACE/builds/x11-64-standard/FoxyAdventure.x86_64
      - name: Export osx
        run: |
          sudo ./Godot_v3.2.4-rc3_linux_headless.64 --path "." --export "osx" $GITHUB_WORKSPACE/builds/osx-standard/FoxyAdventure.zip
      - name: Export win-64
        run: |
          sudo ./Godot_v3.2.4-rc3_linux_headless.64 --path "." --export "win-64" $GITHUB_WORKSPACE/builds/win-64-standard/FoxyAdventure.exe
          tree -a
      - name: Upload a Build Artifact x11-64
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-x11-64
          path: builds/x11-64-standard
      - name: Upload a Build Artifact osx-64
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-osx-64
          path: builds/osx-standard
      - name: Upload a Build Artifact win-64
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-win-64
          path: builds/win-64-standard
