# This is a basic workflow to help you get started with Actions

name: Godot Build Android Standard

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  godot-build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a set of commands using the runners shell
      - name: download godot and export templates
        run: |
          sudo apt install unzip
          sudo apt install tree
          sudo apt install openjdk-11-jdk-headless
          echo *** Downloading Godot Binary ***
          wget https://downloads.tuxfamily.org/godotengine/3.2.4/beta6/Godot_v3.2.4-beta6_linux_headless.64.zip
          echo *** Downloading Godot Server Export Templates ***
          wget https://downloads.tuxfamily.org/godotengine/3.2.4/beta6/Godot_v3.2.4-beta6_export_templates.tpz
          echo *** Downoad Android SDK ***
          wget https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
          echo *** Unzipping Godot Binary ***
          unzip Godot_v3.2.4-beta6_linux_headless.64.zip
          echo *** Unzipping Godot Server Export Templates ***
          unzip Godot_v3.2.4-beta6_export_templates.tpz
          echo *** Installing Android SDK and platform tools ***
          mkdir android-sdk
          touch android-sdk/.gdignore
          unzip sdk-tools-linux-4333796.zip -d android-sdk
          echo *** Installing Godot Server Export Templates ***
          cd /home/runner/
          sudo mkdir -p .local/share/godot
          cd .local/share/godot
          sudo mkdir -p templates/3.2.4.beta6
          sudo cp -r $GITHUB_WORKSPACE/templates/* templates/3.2.4.beta6
          sudo cp $GITHUB_WORKSPACE/editor_settings-3.tres editor_settings-3.tres
          echo *** Exporting Files ***
          cd $GITHUB_WORKSPACE
          sudo mkdir -p builds/android
          sudo ./Godot_v3.2.4-beta6_linux_headless.64 --path "." --export "Android-GithubActions" $GITHUB_WORKSPACE/builds/android/FoxyAdventure.apk
      - name: Upload a Build Artifact android
        uses: actions/upload-artifact@v2.2.2
        with:
          name: build-android
          path: builds/android
